package com.riri.eventhop.feature1.events.entity;

public enum EventCategory {
    ART, SCULPTING, TECHNOLOGY, MUSIC, BAKERY, WEALTH, FILM, DESIGN, BUSINESS, COOKING, DANCE, FASHION, LITERATURE, FITNESS, HEALTH, SCIENCE, TRAVEL, PHOTOGRAPHY, CRAFTS
}
