spring.application.name=eventhop

spring.config.import=file:./.env[.properties]

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=require
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.redis.host=${REDIS_HOST}
spring.redis.port=$REDIS_PORT}
spring.redis.password=${REDIS_PASSWORD}
spring.redis.database=0

#spring.mail.host=${SMTP_HOST}
#spring.mail.port=${SMTP_PORT}
#spring.mail.username=${SMTP_USERNAME}
#spring.mail.password=${SMTP_PASSWORD}
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true

logging.level.org.hibernate=DEBUG
logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

spring.devtools.livereload.enabled=true
spring.devtools.restart.enabled=true